apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "platform.fullname" . }}-ingress
  namespace: asiayo
  annotations:
    # AWS ALB Controller 處理
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
spec:
  ingressClassName: alb 
  rules:
    - host: asiayo.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "platform.fullname" . }}-svc
                port:
                  number: 80